# Generated by Django 2.0.7 on 2018-11-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ZipFile',
        ),
    ]
