# Generated by Django 2.0.7 on 2018-11-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0002_auto_20181109_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipfile',
            options={},
        ),
        migrations.AddField(
            model_name='zipfile',
            name='file_creator',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
