# Generated by Django 2.0.7 on 2018-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0003_auto_20181109_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
