# Generated by Django 2.0.7 on 2018-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0005_list_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
