# Generated by Django 2.0.7 on 2018-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0006_auto_20181109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
