# Generated by Django 2.0.7 on 2018-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0008_auto_20181109_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Subject_list',
            field=models.ManyToManyField(to='eclass.Subject'),
        ),
    ]
