# Generated by Django 2.0.7 on 2018-11-25 11:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('eclass', '0009_list_subject_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='file_subject',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
