# Generated by Django 2.0.7 on 2018-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0011_notefile_notelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='file_url',
            field=models.CharField(max_length=100),
        ),
    ]
