# Generated by Django 2.0.7 on 2018-11-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0012_auto_20181125_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipfile',
            name='file_subject',
        ),
        migrations.AddField(
            model_name='zipfile',
            name='note_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='eclass.NoteList'),
        ),
    ]
