# Generated by Django 2.0.7 on 2018-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0013_auto_20181125_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
