# Generated by Django 2.0.7 on 2018-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0014_auto_20181125_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='recent_downlaod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
