# Generated by Django 2.0.7 on 2018-11-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0015_zipfile_recent_downlaod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfile',
            old_name='recent_downlaod',
            new_name='recent_download',
        ),
    ]
